name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
      env:
        BUNDLE_GITHUB__COM: coord-e:${{ secrets.PAT }}
    - name: Run the default task
      run: bundle exec rake
    - uses: actions/upload-artifact@v4
      with:
        path: '*.pdf'
